use crate::{
    feature_settings::{attr_label, ATTR_ACCURACY, ATTR_HASTE, ATTR_HEALING_MASTERY, ATTR_LUCK, ATTR_MASTERY, ATTR_VERSATILITY},
    model::{AppEvent, DpsRow, DpsSnapshot, ImagineBadge, MechanicRow, MechanicSnapshot, SkillBreakdown, TargetSnapshot, TrackedAttribute},
    proto,
};
use std::{collections::{HashMap, HashSet}, sync::mpsc::Sender, time::{Duration, Instant, SystemTime, UNIX_EPOCH}};

const SYNC_NEAR_ENTITIES:u32=0x06; const SYNC_NEAR_DELTA_INFO:u32=0x2d; const SYNC_TO_ME_DELTA_INFO:u32=0x2e;
const TEAM_INFO:u32=0x01; const TEAM_MEMBER_INFO:u32=0x02; const TEAM_JOIN:u32=0x03; const TEAM_LEAVE:u32=0x04; const TEAM_DISSOLVE:u32=0x0d;
const ATTR_NAME:u64=0x01; const ATTR_MONSTER_ID:u64=0x0a; const ATTR_SKILL_ID:u64=0x64;
const ATTR_HP:u64=11010; const ATTR_MAX_HP:u64=11011; const ATTR_PROFESSION:u64=10160; const ATTR_ABILITY_SCORE:u64=11066; const ATTR_ILLUSION_BREAK:u64=11440;
const ENTITY_PLAYER:i64=10; const ENTITY_MONSTER:i64=1;
const TRACKED_ATTRS:[i32;6]=[ATTR_HEALING_MASTERY,ATTR_LUCK,ATTR_ACCURACY,ATTR_HASTE,ATTR_MASTERY,ATTR_VERSATILITY];

#[derive(Clone,Debug,Default)]struct EntityMeta{name:String,monster_id:i32,hp:i64,max_hp:i64}
#[derive(Clone,Debug,Default)]struct PlayerMeta{actor_uuid:i64,name:String,profession_id:i32,subprofession_id:i32,ability_score:i64,illusion_break:i64,hp:i64,max_hp:i64,attrs:HashMap<i32,i64>}
#[derive(Clone,Debug,Default)]struct SkillStat{damage:i64,healing:i64,hits:u64,crits:u64,luckies:u64,max_value:i64}
#[derive(Clone,Debug,Default)]struct CombatActor{damage:i64,healing:i64,damage_taken:i64,hits:u64,crits:u64,lucky_hits:u64,deaths:u32,is_dead:bool,skills:HashMap<i32,SkillStat>,imagines:HashMap<i32,i32>}

pub struct TelemetryRuntime{
    tx:Sender<AppEvent>, entities:HashMap<i64,EntityMeta>, players:HashMap<i64,PlayerMeta>, team:HashSet<i64>, combat:HashMap<i64,CombatActor>, local_uid:i64,
    encounter_started:Option<Instant>,last_activity:Option<Instant>,last_dps_emit:Instant,last_target:i64,
    mechanics:HashMap<String,MechanicRow>,buff_instances:HashMap<(i64,i32),String>,entity_mechanic_keys:HashMap<i64,Vec<String>>,last_mechanic_emit:Instant,
}
impl TelemetryRuntime{
 pub fn new(tx:Sender<AppEvent>)->Self{let n=Instant::now();Self{tx,entities:HashMap::new(),players:HashMap::new(),team:HashSet::new(),combat:HashMap::new(),local_uid:0,encounter_started:None,last_activity:None,last_dps_emit:n.checked_sub(Duration::from_secs(1)).unwrap_or(n),last_target:0,mechanics:HashMap::new(),buff_instances:HashMap::new(),entity_mechanic_keys:HashMap::new(),last_mechanic_emit:n.checked_sub(Duration::from_secs(1)).unwrap_or(n)}}
 pub fn handle_notify(&mut self,service:u64,method:u32,body:&[u8]){
  if service==proto::TEAM_SERVICE{self.handle_team(method,body);return;} if service!=proto::WORLD_SERVICE{return;}
  match method{
   proto::ENTER_SCENE_METHOD=>{self.reset_scene();self.handle_enter_scene(body);},
   SYNC_NEAR_ENTITIES=>self.handle_near_entities(body),
   SYNC_NEAR_DELTA_INFO=>for d in proto::len_fields(body,1){self.handle_delta(d,None);},
   SYNC_TO_ME_DELTA_INFO=>if let Some(w)=proto::get_len_field(body,1){let outer=signed(proto::get_varint_field(w,5).unwrap_or(0));if let Some(d)=proto::get_len_field(w,1){self.handle_delta(d,(outer!=0).then_some(outer));}},
   _=>{}
  } self.prune_expired_mechanics();
 }
 fn reset_scene(&mut self){self.entities.clear();self.combat.clear();self.encounter_started=None;self.last_activity=None;self.last_target=0;self.mechanics.clear();self.buff_instances.clear();self.entity_mechanic_keys.clear();for uid in self.team.clone(){self.combat.entry(uid).or_default();}let _=self.tx.send(AppEvent::Dps(DpsSnapshot::default()));self.emit_mechanics(true);}
 fn handle_enter_scene(&mut self,body:&[u8]){if let Some(info)=proto::get_len_field(body,1){if let Some(player)=proto::get_len_field(info,2){let uuid=signed(proto::get_varint_field(player,1).unwrap_or(0));if uuid!=0{self.local_uid=uuid>>16;self.team.insert(self.local_uid);self.combat.entry(self.local_uid).or_default();self.update_entity_from_attrs(uuid,proto::get_len_field(player,3));}}}self.emit_dps();self.emit_mechanics(true);}
 fn handle_team(&mut self,method:u32,body:&[u8]){if method==TEAM_DISSOLVE{self.team.clear();if self.local_uid>0{self.team.insert(self.local_uid);}self.retain_team_rows();self.emit_dps();return;}if method==TEAM_LEAVE{let before=self.team.clone();self.scan_team_members(body);if self.team==before{self.team.retain(|u|*u==self.local_uid);}self.retain_team_rows();self.emit_dps();return;}if matches!(method,TEAM_INFO|TEAM_MEMBER_INFO|TEAM_JOIN){self.scan_team_members(body);for uid in self.team.clone(){self.combat.entry(uid).or_default();}self.emit_dps();}}
 fn retain_team_rows(&mut self){if self.encounter_started.is_none(){self.combat.retain(|uid,_|self.team.contains(uid));}}
 fn scan_team_members(&mut self,data:&[u8]){let mut found=Vec::new();scan_member_messages(data,0,&mut found);for m in found{if m.uid<=0{continue;}self.team.insert(m.uid);let p=self.players.entry(m.uid).or_default();if !m.name.is_empty(){p.name=m.name;}if m.profession_id>0{p.profession_id=m.profession_id;}if m.hp>0{p.hp=m.hp;}if m.max_hp>0{p.max_hp=m.max_hp;}self.combat.entry(m.uid).or_default();}}
 fn handle_near_entities(&mut self,body:&[u8]){let mut changed=false;for e in proto::len_fields(body,1){let uuid=signed(proto::get_varint_field(e,1).unwrap_or(0));if uuid==0{continue;}self.update_entity_from_attrs(uuid,proto::get_len_field(e,3));let mid=self.entities.get(&uuid).map(|x|x.monster_id).unwrap_or(0);if let Some((label,dur,pri))=monster_rule(mid){let key=format!("entity:{uuid}:{mid}");self.mechanics.insert(key.clone(),mechanic_row(key.clone(),label,None,dur,dur==0,pri));self.entity_mechanic_keys.entry(uuid).or_default().push(key);changed=true;}}for g in proto::len_fields(body,2){let uuid=signed(proto::get_varint_field(g,1).unwrap_or(0));self.entities.remove(&uuid);if let Some(keys)=self.entity_mechanic_keys.remove(&uuid){for k in keys{changed|=self.mechanics.remove(&k).is_some();}}}if changed{self.emit_mechanics(true);}self.emit_dps();}
 fn handle_delta(&mut self,delta:&[u8],outer:Option<i64>){let raw=signed(proto::get_varint_field(delta,1).unwrap_or(0));let uuid=if raw!=0{raw}else{outer.unwrap_or(0)};if uuid==0{return;}if let Some(attrs)=proto::get_len_field(delta,2){self.update_entity_from_attrs(uuid,Some(attrs));if let Some(skill)=attr_varint(attrs,ATTR_SKILL_ID).map(|v|v as i32){if let Some((label,dur,pri))=skill_rule(skill){let key=format!("skill:{uuid}:{skill}:{}",now_ms()/250);self.mechanics.insert(key.clone(),mechanic_row(key,label,self.display_target(uuid),dur,false,pri));self.emit_mechanics(false);}}}if let Some(effects)=proto::get_len_field(delta,7){for dmg in proto::len_fields(effects,2){self.apply_damage(uuid,dmg);}}if let Some(b)=proto::get_len_field(delta,10){for e in proto::len_fields(b,2){self.apply_buff(uuid,e);}}}
 fn update_entity_from_attrs(&mut self,uuid:i64,attrs:Option<&[u8]>){let Some(attrs)=attrs else{return;};if entity_kind(uuid)==ENTITY_PLAYER{let uid=uuid>>16;let p=self.players.entry(uid).or_default();p.actor_uuid=uuid;for a in proto::len_fields(attrs,2){let id=proto::get_varint_field(a,1).unwrap_or(0);let Some(raw)=proto::get_len_field(a,2)else{continue;};let value=raw_signed(raw);match id{ATTR_NAME=>if let Some(n)=decode_name(raw){p.name=n;},ATTR_PROFESSION=>if let Some(v)=value{p.profession_id=v as i32;},ATTR_ABILITY_SCORE=>if let Some(v)=value{p.ability_score=v;},ATTR_ILLUSION_BREAK=>if let Some(v)=value{p.illusion_break=v;},ATTR_HP=>if let Some(v)=value{p.hp=v;if v>0{self.combat.entry(uid).or_default().is_dead=false;}},ATTR_MAX_HP=>if let Some(v)=value{p.max_hp=v;},_=>if TRACKED_ATTRS.contains(&(id as i32)){if let Some(v)=value{p.attrs.insert(id as i32,v);}}}}if self.team.contains(&uid)||uid==self.local_uid{self.combat.entry(uid).or_default();}}
  else{let m=self.entities.entry(uuid).or_default();for a in proto::len_fields(attrs,2){let id=proto::get_varint_field(a,1).unwrap_or(0);let Some(raw)=proto::get_len_field(a,2)else{continue;};match id{ATTR_NAME=>if let Some(n)=decode_name(raw){m.name=n;},ATTR_MONSTER_ID=>if let Some(v)=raw_varint(raw){m.monster_id=v.min(i32::MAX as u64)as i32;},ATTR_HP=>if let Some(v)=raw_signed(raw){m.hp=v;},ATTR_MAX_HP=>if let Some(v)=raw_signed(raw){m.max_hp=v;},_=>{}}}}
 }
 fn apply_damage(&mut self,target_uuid:i64,d:&[u8]){let dtype=proto::get_varint_field(d,4).unwrap_or(0)as i32;let miss=proto::get_varint_field(d,2).unwrap_or(0)!=0||dtype==1;if miss||matches!(dtype,3|5){return;}let top=signed(proto::get_varint_field(d,21).unwrap_or(0));let raw_att=signed(proto::get_varint_field(d,11).unwrap_or(0));let attacker_uuid=if top!=0{top}else{raw_att};let attacker_uid=if attacker_uuid!=0&&entity_kind(attacker_uuid)==ENTITY_PLAYER{attacker_uuid>>16}else{0};let skill=proto::get_varint_field(d,12).unwrap_or(0)as i32;let owner_level=proto::get_varint_field(d,13).unwrap_or(0).min(i32::MAX as u64)as i32;let raw=signed(proto::get_varint_field(d,6).unwrap_or(0));let lucky=signed(proto::get_varint_field(d,8).unwrap_or(0));let lessen=signed(proto::get_varint_field(d,9).unwrap_or(0));let mut value=if lucky!=0{lucky}else{raw};if value<0{value=lessen.max(0);}if value<=0{return;}if let Some(target_attrs)=proto::get_len_field(d,19){self.update_entity_from_attrs(target_uuid,Some(target_attrs));}
  let now=Instant::now();if self.last_activity.is_some_and(|x|x.elapsed()>=Duration::from_secs(10)){self.reset_encounter_keep_roster();}self.encounter_started.get_or_insert(now);self.last_activity=Some(now);
  let is_dead=proto::get_varint_field(d,15).unwrap_or(0)!=0;
  if dtype==2{if attacker_uid>0{let a=self.combat.entry(attacker_uid).or_default();a.healing=a.healing.saturating_add(value);self.apply_skill(attacker_uid,skill,value,true,lucky!=0,proto::get_varint_field(d,5).unwrap_or(0)&1!=0);self.record_imagine(attacker_uid,skill,owner_level);}}
  else{if entity_kind(target_uuid)==ENTITY_MONSTER&&attacker_uid>0{self.last_target=target_uuid;let a=self.combat.entry(attacker_uid).or_default();a.damage=a.damage.saturating_add(value);a.hits=a.hits.saturating_add(1);if proto::get_varint_field(d,5).unwrap_or(0)&1!=0{a.crits=a.crits.saturating_add(1);}if lucky!=0{a.lucky_hits=a.lucky_hits.saturating_add(1);}self.apply_skill(attacker_uid,skill,value,false,lucky!=0,proto::get_varint_field(d,5).unwrap_or(0)&1!=0);self.record_imagine(attacker_uid,skill,owner_level);}if entity_kind(target_uuid)==ENTITY_PLAYER{let uid=target_uuid>>16;let a=self.combat.entry(uid).or_default();a.damage_taken=a.damage_taken.saturating_add(value);if is_dead&&!a.is_dead{a.deaths=a.deaths.saturating_add(1);}a.is_dead=is_dead;}}
  if self.last_dps_emit.elapsed()>=Duration::from_millis(100){self.emit_dps();}
 }
 fn apply_skill(&mut self,uid:i64,skill:i32,value:i64,heal:bool,lucky:bool,crit:bool){let s=self.combat.entry(uid).or_default().skills.entry(skill).or_default();if heal{s.healing=s.healing.saturating_add(value);}else{s.damage=s.damage.saturating_add(value);}s.hits=s.hits.saturating_add(1);if crit{s.crits=s.crits.saturating_add(1);}if lucky{s.luckies=s.luckies.saturating_add(1);}s.max_value=s.max_value.max(value);}
 fn record_imagine(&mut self,uid:i64,skill:i32,tier:i32){if is_imagine_skill(skill){self.combat.entry(uid).or_default().imagines.entry(skill).and_modify(|t|*t=(*t).max(tier)).or_insert(tier);}}
 fn reset_encounter_keep_roster(&mut self){self.combat.clear();for uid in self.team.clone(){self.combat.entry(uid).or_default();}if self.local_uid>0{self.combat.entry(self.local_uid).or_default();}self.encounter_started=None;self.last_target=0;}
 fn emit_dps(&mut self){self.last_dps_emit=Instant::now();let ms=self.encounter_started.map(|x|x.elapsed().as_millis()as u64).unwrap_or(0).max(1);let sec=ms as f64/1000.0;let td:i64=self.combat.values().map(|x|x.damage).sum();let th:i64=self.combat.values().map(|x|x.healing).sum();let tt:i64=self.combat.values().map(|x|x.damage_taken).sum();let mut uids:HashSet<i64>=self.combat.keys().copied().collect();uids.extend(self.team.iter().copied());if self.local_uid>0{uids.insert(self.local_uid);}let mut rows=Vec::with_capacity(uids.len());for uid in uids{let stat=self.combat.get(&uid).cloned().unwrap_or_default();let meta=self.players.get(&uid).cloned().unwrap_or_default();let mut skills:Vec<SkillBreakdown>=stat.skills.iter().map(|(id,s)|SkillBreakdown{skill_id:*id,name:skill_name(*id),damage:s.damage,healing:s.healing,hits:s.hits,crits:s.crits,lucky_hits:s.luckies,max_value:s.max_value}).collect();skills.sort_by(|a,b|(b.damage+b.healing).cmp(&(a.damage+a.healing)));let mut imagines:Vec<ImagineBadge>=stat.imagines.iter().map(|(id,tier)|{let(n,key)=imagine_info(*id);ImagineBadge{skill_id:*id,name:n,tier:*tier,icon_key:key}}).collect();imagines.sort_by_key(|x|x.skill_id);rows.push(DpsRow{actor_uuid:meta.actor_uuid,uid,name:if meta.name.trim().is_empty(){format!("Player {uid}")}else{meta.name},profession_id:meta.profession_id,subprofession_id:meta.subprofession_id,subprofession_name:subprofession_name(meta.subprofession_id).into(),ability_score:meta.ability_score,illusion_break:meta.illusion_break,damage:stat.damage,healing:stat.healing,damage_taken:stat.damage_taken,dps:stat.damage as f64/sec.max(.001),damage_share:pct(stat.damage,td),healing_share:pct(stat.healing,th),tank_share:pct(stat.damage_taken,tt),hits:stat.hits,crits:stat.crits,lucky_hits:stat.lucky_hits,deaths:stat.deaths,is_dead:stat.is_dead,imagines,skills});}rows.sort_by(|a,b|b.damage.cmp(&a.damage).then_with(||b.healing.cmp(&a.healing)));let target=self.target_snapshot();let _=self.tx.send(AppEvent::Dps(DpsSnapshot{encounter_ms:ms,total_damage:td,total_healing:th,total_damage_taken:tt,target,rows}));}
 fn target_snapshot(&self)->Option<TargetSnapshot>{let m=self.entities.get(&self.last_target)?;if self.last_target==0{return None;}Some(TargetSnapshot{entity_uuid:self.last_target,name:if m.name.trim().is_empty(){if m.monster_id>0{format!("Target {}",m.monster_id)}else{"Target".into()}}else{m.name.clone()},hp:m.hp,max_hp:m.max_hp,enrage_remaining_ms:None})}
 fn apply_buff(&mut self,host:i64,e:&[u8]){let typ=proto::get_varint_field(e,1).unwrap_or(0)as i32;let bu=proto::get_varint_field(e,2).unwrap_or(0)as i32;if matches!(typ,2|6){if let Some(k)=self.buff_instances.remove(&(host,bu)){if self.mechanics.remove(&k).is_some(){self.emit_mechanics(false);}}return;}if !matches!(typ,1|3|4|5){return;}for logic in proto::len_fields(e,5){if proto::get_varint_field(logic,1).unwrap_or(0)!=18{continue;}let Some(info)=proto::get_len_field(logic,2)else{continue;};let id=proto::get_varint_field(info,2).unwrap_or(0)as i32;let Some((label,def,pri))=buff_rule(id)else{continue;};let duration=proto::get_varint_field(info,11).unwrap_or(0).min(300000)as u64;let dur=if duration>0{duration}else{def};let key=format!("buff:{host}:{bu}:{id}");self.mechanics.insert(key.clone(),mechanic_row(key.clone(),label,self.display_target(host),dur,dur==0,pri));self.buff_instances.insert((host,bu),key);self.emit_mechanics(false);}}
 fn display_target(&self,uuid:i64)->Option<String>{if entity_kind(uuid)!=ENTITY_PLAYER{return None;}let uid=uuid>>16;self.players.get(&uid).map(|x|x.name.trim()).filter(|n|!n.is_empty()).map(str::to_string).or_else(||Some(format!("Player {uid}")))}
 fn prune_expired_mechanics(&mut self){let n=now_ms();let before=self.mechanics.len();self.mechanics.retain(|_,r|r.persistent||r.expires_unix_ms<=0||r.expires_unix_ms>n);if before!=self.mechanics.len(){self.emit_mechanics(true);}}
 fn emit_mechanics(&mut self,force:bool){if !force&&self.last_mechanic_emit.elapsed()<Duration::from_millis(50){return;}self.last_mechanic_emit=Instant::now();let n=now_ms();let mut rows:Vec<MechanicRow>=self.mechanics.values().filter(|r|r.persistent||r.expires_unix_ms<=0||r.expires_unix_ms>n).cloned().collect();rows.sort_by(|a,b|b.priority.cmp(&a.priority).then_with(||a.expires_unix_ms.cmp(&b.expires_unix_ms)));rows.truncate(20);let tracked_attributes=self.players.get(&self.local_uid).map(|p|TRACKED_ATTRS.iter().map(|id|TrackedAttribute{attr_id:*id,label:attr_label(*id).into(),value:*p.attrs.get(id).unwrap_or(&0)}).collect()).unwrap_or_default();let _=self.tx.send(AppEvent::Mechanics(MechanicSnapshot{tracked_attributes,rows}));}
}

#[derive(Default)]struct TeamCandidate{uid:i64,name:String,profession_id:i32,hp:i64,max_hp:i64}
fn scan_member_messages(data:&[u8],depth:usize,out:&mut Vec<TeamCandidate>){if depth>5||data.is_empty()||data.len()>1024*1024{return;}let uid=signed(proto::get_varint_field(data,1).unwrap_or(0));let name=proto_string(data,3).unwrap_or_default();let profession=proto::get_varint_field(data,4).unwrap_or(0)as i32;let hp=signed(proto::get_varint_field(data,8).unwrap_or(0));let max_hp=signed(proto::get_varint_field(data,9).unwrap_or(0));if uid>0&&!name.trim().is_empty()&&(profession>0||max_hp>0){out.push(TeamCandidate{uid,name,profession_id:profession,hp,max_hp});}for f in 1..=24{for child in proto::len_fields(data,f){if child.len()<data.len(){scan_member_messages(child,depth+1,out);}}}}
fn proto_string(data:&[u8],field:u32)->Option<String>{let b=proto::get_len_field(data,field)?;if b.is_empty()||b.len()>256{return None;}let s=std::str::from_utf8(b).ok()?.replace(|c:char|matches!(c,'\0'|'\r'|'\n')," ").trim().to_string();(!s.is_empty()).then_some(s)}
fn attr_varint(attrs:&[u8],wanted:u64)->Option<u64>{for a in proto::len_fields(attrs,2){if proto::get_varint_field(a,1)==Some(wanted){return raw_varint(proto::get_len_field(a,2)?);}}None}
fn raw_varint(raw:&[u8])->Option<u64>{let mut p=0;proto::read_varint(raw,&mut p)} fn raw_signed(raw:&[u8])->Option<i64>{raw_varint(raw).map(signed)}
fn decode_name(raw:&[u8])->Option<String>{if raw.is_empty(){return None;}let mut p=0;let decoded=if let Some(len)=proto::read_varint(raw,&mut p){let l=usize::try_from(len).ok()?;if l>0&&p.checked_add(l)==Some(raw.len()){&raw[p..]}else if raw.len()>1{&raw[1..]}else{return None;}}else if raw.len()>1{&raw[1..]}else{return None;};let t=std::str::from_utf8(decoded).ok()?.replace(|c:char|matches!(c,'\r'|'\n'|'\0')," ").trim().to_string();(!t.is_empty()).then(||t.chars().take(128).collect())}
fn signed(v:u64)->i64{v as i64} fn entity_kind(uuid:i64)->i64{(uuid>>6)&0x1f} fn now_ms()->i64{SystemTime::now().duration_since(UNIX_EPOCH).map(|d|d.as_millis().min(i64::MAX as u128)as i64).unwrap_or(0)} fn pct(v:i64,total:i64)->f64{if total>0{v.max(0)as f64*100.0/total as f64}else{0.0}}
fn mechanic_row(key:String,label:&str,target:Option<String>,dur:u64,persistent:bool,priority:u8)->MechanicRow{let n=now_ms();MechanicRow{key,label:label.into(),target,created_unix_ms:n,expires_unix_ms:if dur>0{n.saturating_add(dur as i64)}else{0},persistent,priority}}
fn is_imagine_skill(id:i32)->bool{matches!(id,3903|3920|3921)||(3900..=3999).contains(&id)}
fn imagine_info(id:i32)->(String,String){match id{3903=>("Brigand Leader".into(),"BL".into()),3920=>("Airona".into(),"AI".into()),3921=>("Tina".into(),"TI".into()),_=>(format!("Battle Imagine {id}"),"BI".into())}}
fn skill_name(id:i32)->String{match id{3903=>"Brigand Leader".into(),3920=>"Airona".into(),3921=>"Tina".into(),0=>"Unknown".into(),_=>format!("Skill {id}")}}
fn subprofession_name(id:i32)->&'static str{match id{1001=>"Iai",1002=>"Moonstrike",2001=>"Smite",2002=>"Ice Spear",3001=>"Skyward",3002=>"Vanguard",4001=>"Earthfort",4002=>"Block",5001=>"Wildpack",5002=>"Falconry",8001=>"Lifebind",8002=>"Smite",9001=>"Dissonance",9002=>"Concerto",10001=>"Recovery",10002=>"Shield",11001=>"Taming",11002=>"Wildpack",12001=>"Crystal",12002=>"Frostbeam",_=>""}}
fn monster_rule(id:i32)->Option<(&'static str,u64,u8)>{Some(match id{2106=>("Correct portal",0,3),300086=>("Pizza danger - SLOW",0,3),300089=>("Pizza danger - FAST",0,3),33904|33905=>("Tower activating",40000,2),3340219=>("Ice wave",0,3),3340220=>("Water wave",0,3),10330051=>("Pinball",6000,2),_=>return None})}
fn skill_rule(id:i32)->Option<(&'static str,u64,u8)>{Some(match id{111103=>("Gravity Blast",8500,3),3390117|3390123=>("Clone charge - LEFT",10000,3),3390118|3390124=>("Clone charge - RIGHT",10000,3),3340245=>("Pizza danger",7000,3),10310062=>("Electromagnetic ring - INNER",6000,3),10310063=>("Electromagnetic ring - MID",6000,3),10310064=>("Electromagnetic ring - OUTER",6000,3),470125|470132=>("Pair mechanic - SETTLE",5000,3),470119=>("Shadow phase",8000,3),470112=>("Chain - NEAR circle",4000,3),470113=>("Chain - FAR circle",4000,3),_=>return None})}
fn buff_rule(id:i32)->Option<(&'static str,u64,u8)>{Some(match id{821076=>("Sticky Bomb",8000,3),884101|884106|884122=>("Tower activating",40000,2),884102=>("Tower complete - BLUE",5000,1),884103=>("Tower complete - GOLD",5000,1),884129=>("Energy Pillar",10000,3),884141=>("Energy Pillar - SHORT",8000,3),884162=>("Charge target - LEFT",10000,3),884163=>("Charge target - RIGHT",10000,3),884168=>("Charge target - RANDOM",10000,3),884169=>("Puzzle mark #1",12000,3),884170=>("Puzzle mark #2",12000,3),510571=>("Heavy Wound",10000,3),841519=>("Red Bind",10000,3),841509=>("Wudi Slash",10000,3),829214=>("Phase - EDGE",10000,2),829215=>("Phase - CORNER",10000,2),829327=>("Phase mirage - TOP LEFT",10000,2),829328=>("Phase mirage - MID LEFT",10000,2),829329=>("Phase mirage - BOTTOM LEFT",10000,2),829330=>("Phase mirage - TOP RIGHT",10000,2),829331=>("Phase mirage - MID RIGHT",10000,2),829332=>("Phase mirage - BOTTOM RIGHT",10000,2),829104=>("Electromagnetic Pulse A",10000,3),829105=>("Electromagnetic Pulse B",10000,3),829106=>("Electromagnetic Pulse C",10000,3),829115|829116|829304|829305=>("Share",10000,3),829306|829307=>("Decay",10000,3),829308|829309=>("Spread",10000,3),829316=>("Causal Jump",10000,3),829217=>("Normal target",10000,3),829245=>("Decay target",10000,3),829226=>("Hit order #1",10000,3),829227=>("Hit order #2",10000,3),829228=>("Hit order #3",10000,3),829323|829324|829326=>("Kill mark",10000,3),829314=>("Pinball cast",6000,3),883602=>("Dual mark - ICE",10000,3),883603=>("Dual mark - WATER",10000,3),883633=>("Pizza - ORANGE",8000,2),883634=>("Pizza - PURPLE",8000,2),884659=>("Pair mark",25000,3),884664=>("Pair swap",25000,2),884660=>("Pair settle",6000,3),884661=>("Pair penalty",6000,3),884614=>("Wheel - BLUE / GROUP",10000,3),884615=>("Wheel - RED / SOLO",10000,3),884616=>("Wheel - DOOM",10000,3),884641=>("Energy Ball target",10000,3),884609=>("Chain - NEAR",8000,3),884610=>("Chain - FAR",8000,3),_=>return None})}

#[cfg(test)]mod tests{use super::*;#[test]fn entity_layout(){let p=(123_i64<<16)|(10<<6);let m=(456_i64<<16)|(1<<6);assert_eq!(entity_kind(p),ENTITY_PLAYER);assert_eq!(entity_kind(m),ENTITY_MONSTER);}#[test]fn imagine_mapping(){assert_eq!(imagine_info(3921).0,"Tina");assert!(is_imagine_skill(3903));}#[test]fn shares(){assert!((pct(25,100)-25.0).abs()<0.001);}}
